name: Deploy a hosting

on:
  push:
    branches:
      - main

jobs:
  ftp-deploy:
    name: Build y subir por FTP
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Obtener código
        uses: actions/checkout@v4

      - name: 🟢 Configurar Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: 📦 Instalar dependencias
        run: npm ci

      - name: 🏗️ Build
        run: npm run build

      - name: 🚀 Subir por FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./dist/
          server-dir: ./
          dangerous-clean-slate: true
